name: Wenwuwu Electron Forge Action
author: Wenwu Wu
description: GitHub Action for building and releasing Electron apps using electron-forge

inputs:
  github_token:
    description: GitHub authentication token
    required: true
  mac_certs:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_certs_password:
    description: Password for decrypting `mac_certs`
    required: false
  release:
    description: Whether the app should be released after a successful build
    required: false
    default: false
  windows_certs:
    description: Base64-encoded code signing certificate for Windows
    required: false
  windows_certs_password:
    description: Password for decrypting `windows_certs`
    required: false
  win_certs_path:
    description: Path to code signing certificate pfx file for Windows
    required: false
  win_certs_password:
    description: Password for decrypting file of `win_certs_path`
    required: false
  package_root:
    description: Directory where NPM/Yarn commands should be run
    required: false
    default: "."
  rebuild:
    description: Whether the app should run rebuild script
    required: false
    default: false
  build_script_name:
    description: Name of the optional NPM build script which is executed before `electron-builder`
    required: false
    default: build
  skip_build:
    description: Whether the action should execute the NPM build script before running `electron-builder`
    required: false
    default: false
  use_vue_cli:
    description: Whether to run `electron-builder` using the Vue CLI plugin instead of calling the command directly
    required: false
    default: false

  # Deprecated
  app_root:
    description: Directory where `electron-builder` commands should be run
    required: false

runs:
  using: node16
  main: index.js

branding:
  icon: upload-cloud
  color: blue
